name = "todoapi"
compatibility_date = "2023-12-01"

# [vars]
# MY_VARIABLE = "production_value"

[[kv_namespaces]]
binding = "TODOKV"
id = "f088e159881448e1b1df201ed3bd043c"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
